"""
test_flex_with_rigidity.py
==========================
Demonstrates the mathematical artefact that arises when a *rigid-disk*
identification model is applied to data generated by a *flexible-disk* rotor.

Background
----------
When the true disk is flexible, the Schur-condensed disk influence term
D_disk(omega) is non-circulant.  A rigid-disk identifier cannot distinguish
this contribution from aerodynamic forcing, so it absorbs the disk dynamics
into the aerodynamic influence coefficients.  The result is a jagged (high
nodal-diameter energy) TW coefficient curve — the artefact of Hall & Hall
(2024).

Workflow
--------
1.  Generate synthetic data with the flexible-disk model.
2.  Identify with AeromechanicalIdentification (rigid-disk model, no bounds).
3.  Diagnose overfitting: compare J_opt vs J_true and the TW coefficient
    deviation from the smooth physical reference.
4.  Compute Cramér-Rao bounds and generate three diagnostic plots.

Dependencies
------------
    auxSolver.aero_ident      — AeromechanicalIdentification
    auxSolver.data_generation — generate_rotor_data
    auxSolver.plot_aero       — AeroPlotter
    cyipopt                   — Python interface to IPOPT
"""

import numpy as np
from cyipopt import minimize_ipopt

from auxSolver.aero_ident import AeromechanicalIdentification
from auxSolver.data_generation import generate_rotor_data
from auxSolver.plot_aero import AeroPlotter


# ---------------------------------------------------------------------------
# Cached evaluator with parameter scaling
# ---------------------------------------------------------------------------

class CachedEvaluator:
    """
    Caching wrapper with diagonal parameter scaling for IPOPT.

    Parameters
    ----------
    ident_problem : AeromechanicalIdentification
    scale_factors : array-like, shape (5N-1,)
    """

    def __init__(self, ident_problem, scale_factors):
        self.problem = ident_problem
        self.scales  = np.asarray(scale_factors, dtype=np.float64)
        self._cache_key  = None
        self._cache_J    = None
        self._cache_grad = None

    def _update(self, theta_scaled):
        key = theta_scaled.tobytes()
        if key != self._cache_key:
            theta_phys = theta_scaled * self.scales
            J, g_phys  = self.problem.compute_objective_and_gradient(theta_phys)
            self._cache_J    = J
            self._cache_grad = g_phys * self.scales
            self._cache_key  = key

    def objective(self, theta_scaled):
        """Return the cached objective value."""
        self._update(theta_scaled)
        return self._cache_J

    def gradient(self, theta_scaled):
        """Return the cached scaled gradient."""
        self._update(theta_scaled)
        return self._cache_grad


# ---------------------------------------------------------------------------
# Main routine
# ---------------------------------------------------------------------------

def isolate_aerodynamic_artifact():
    """
    Quantify and visualise the aerodynamic artefact from model mismatch.

    The identifier is intentionally given no bounds so it can freely overfit
    the data, absorbing all disk dynamics into the aerodynamic coefficients.
    """

    # ------------------------------------------------------------------
    # 1.  Simulation parameters
    # ------------------------------------------------------------------
    N           = 33
    omega_0     = 17000.0
    T           = 200
    omega_t     = np.linspace(16250.0, 17750.0, T)
    noise_level = 1e-4

    print("=" * 65)
    print("  Aerodynamic artefact from flexible disk — Hall & Hall 2024")
    print("=" * 65)

    # ------------------------------------------------------------------
    # 2.  Synthetic data from the flexible-disk model
    # ------------------------------------------------------------------
    print("\n[1/4] Generating data: FLEXIBLE-DISK model ...")
    result     = generate_rotor_data('flexible', omega_t, omega_0, noise_level)
    y_measured = result['y_measured']
    theta_true = result['theta_true']

    # Physical aerodynamic coefficients (Table 1).
    # In TW space these produce a smooth, low-ND-energy curve — the signature
    # of short-range blade-to-blade aerodynamic interaction.
    # The rigid-disk identifier cannot separate this from disk dynamics and
    # produces a jagged TW curve (the artefact).
    a0_circ_true = np.zeros(N)
    a1_circ_true = np.zeros(N)
    a1_circ_true[0]   = 0.0050   # self-damping
    a0_circ_true[1]   = 0.00001;  a1_circ_true[1]   = 0.0010
    a0_circ_true[2]   = 0.00000;  a1_circ_true[2]   = 0.0015
    a0_circ_true[N-2] = 0.00000;  a1_circ_true[N-2] = 0.0020
    a0_circ_true[N-1] = 0.00000;  a1_circ_true[N-1] = 0.0025

    # Smooth TW reference used in the artefact comparison plot
    A_tw_true_smooth = np.fft.fft(a0_circ_true + 1j * a1_circ_true)

    # ------------------------------------------------------------------
    # 3.  Rigid-disk identification model
    # ------------------------------------------------------------------
    print("[2/4] Initialising identification model: RIGID DISK ...")
    ident_problem = AeromechanicalIdentification(y_measured, omega_t, omega_0, N)

    num_params = 5 * N - 1
    idx_d0 = 0
    idx_a0 = N
    idx_fr = N + (N - 1) + N

    # Diagonal scaling — maps each block to O(1) magnitude
    scale_factors = np.ones(num_params)
    scale_factors[idx_d0 : idx_a0] = 1e-2   # mistuning  O(1e-2)
    scale_factors[idx_a0 : idx_fr] = 1e-3   # aero       O(1e-3)
    scale_factors[idx_fr :]        = 1e-1   # forcing    O(1e-1)

    np.random.seed(99)
    theta_initial        = 1e-5 * np.ones(num_params)
    theta_initial_scaled = theta_initial / scale_factors

    evaluator = CachedEvaluator(ident_problem, scale_factors)

    # ------------------------------------------------------------------
    # 4.  Unconstrained IPOPT optimisation
    #     No bounds are imposed so the solver can overfit freely,
    #     absorbing flexible-disk dynamics into the aerodynamic parameters.
    # ------------------------------------------------------------------
    print(f"[3/4] Running IPOPT ({num_params} parameters, unconstrained) ...")
    ipopt_options = {
        'max_iter'                  : 20000,
        'tol'                       : 1e-9,
        'acceptable_tol'            : 1e-6,
        'print_level'               : 5,
        'hessian_approximation'     : 'limited-memory',
        'limited_memory_max_history': 1,
        'limited_memory_update_type': 'sr1',
    }

    res = minimize_ipopt(
        fun    = evaluator.objective,
        x0     = theta_initial_scaled,
        jac    = evaluator.gradient,
        bounds = None,
        options= ipopt_options,
    )

    theta_opt = res.x * scale_factors

    # ------------------------------------------------------------------
    # 5.  Overfitting diagnostics
    # ------------------------------------------------------------------
    J_opt  = ident_problem.objective(theta_opt)
    J_true = ident_problem.objective(theta_true)

    print(f"\n{'─'*55}")
    print(f"  J (rigid model, optimised)       : {J_opt:.4e}")
    print(f"  J (true params, rigid model)     : {J_true:.4e}")
    print(f"  Ratio J_true / J_opt             : {J_true / J_opt:.2f}")
    print(f"  (ratio >> 1 confirms overfitting)")
    print(f"{'─'*55}")

    _, a0_opt, a1_opt, _, _ = ident_problem.unpack_theta(theta_opt)
    A_tw_opt = np.fft.fft(a0_opt + 1j * a1_opt)
    print(f"\n  Artefact check — std dev relative to smooth reference:")
    print(f"    std(Real ΔA_tw) = "
          f"{np.std(np.real(A_tw_opt) - np.real(A_tw_true_smooth)):.4e}")
    print(f"    std(Imag ΔA_tw) = "
          f"{np.std(np.imag(A_tw_opt) - np.imag(A_tw_true_smooth)):.4e}")
    print(f"  (values >> noise={noise_level:.0e} indicate a significant artefact)\n")

    # ------------------------------------------------------------------
    # 6.  Cramér-Rao bounds
    # ------------------------------------------------------------------
    sigma_theta = ident_problem.compute_cramer_rao_bounds(theta_opt, noise_level ** 2)

    # ------------------------------------------------------------------
    # 7.  Diagnostic plots
    # ------------------------------------------------------------------
    print("[4/4] Generating plots ...")
    plotter = AeroPlotter(
        sim_problem      = ident_problem,
        omega_t          = omega_t,
        y_measured       = y_measured,
        N                = N,
        theta_true       = theta_true,
        theta_opt        = theta_opt,
        theta_initial    = theta_initial,
        sigma_theta      = sigma_theta,
        A_tw_true_smooth = A_tw_true_smooth,
    )

    plotter.plot_response_envelope()
    plotter.plot_parameters_2x2()
    plotter.plot_artifact_comparison()

    print("\nDone.")


if __name__ == '__main__':
    isolate_aerodynamic_artifact()
